### ISSUE TITLE
separator_index < line.size() in function 'ReadDarknetFromCfgStream'

### ISSUE THREAD

**Issue by monxarat** [Pranav1007/Social-Distance-Detector#1]
Hi guys,

When I ran the bellow error has occurred.

```
$ python3 run.py -m v -p media/test.mp4
Traceback (most recent call last):
  File "../Social-Distance-Detector/run.py", line 3, in <module>
    from utilities.helper import video, image, webcam
  File "../Social-Distance-Detector/utilities/helper.py", line 3, in <module>
    from .functions import main_func, findObjects, load_model
  File "../Social-Distance-Detector/utilities/functions.py", line 8, in <module>
    classNames, modelNet = load_model()                 # Load the yolo model
  File "../Social-Distance-Detector/utilities/model.py", line 24, in load_model
    modelNet = cv2.dnn.readNetFromDarknet(modelConfig, modelWeights)    # Loading the YOLO Object Detector Model
cv2.error: OpenCV(4.5.3) /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-req-build-vy_omupv/opencv/modules/dnn/src/darknet/darknet_io.cpp:659: error: (-215:Assertion failed) separator_index < line.size() in function 'ReadDarknetFromCfgStream'
```

**Comment by monxarat** [comment]
I missing content of files `yolov3.cfg` `yolov3.weights` `coco.names`
